/*
 * Pure Solo Gateway
 * Web Dashboard UI Content
 */
#include "web.h"

static const char * const html_dashboard = 
"<!DOCTYPE html>\n"
"<html lang='en'>\n"
"<head>\n"
"    <meta charset='UTF-8'>\n"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
"    <title>Pure Solo Gateway</title>\n"
"    <style>\n"
"        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #121212; color: #e0e0e0; margin: 0; padding: 20px; }\n"
"        .container { max-width: 900px; margin: 0 auto; }\n"
"        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #333; padding-bottom: 10px; margin-bottom: 20px; }\n"
"        .header h1 { margin: 0; font-size: 24px; color: #4caf50; }\n"
"        .status-indicator { display: flex; align-items: center; font-size: 14px; font-weight: bold; }\n"
"        .dot { height: 12px; width: 12px; background-color: #4caf50; border-radius: 50%; display: inline-block; margin-right: 8px; box-shadow: 0 0 8px #4caf50; }\n"
"        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; }\n"
"        .card { background-color: #1e1e1e; border-radius: 8px; padding: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); border: 1px solid #2a2a2a; }\n"
"        .card h3 { margin: 0 0 10px 0; font-size: 13px; color: #888; text-transform: uppercase; letter-spacing: 1px; }\n"
"        .card p { margin: 0; font-size: 26px; font-weight: bold; color: #fff; }\n"
"        .card .subtext { font-size: 12px; color: #666; margin-top: 5px; font-weight: normal; }\n"
"        .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #555; }\n"
"        table { width: 100%; border-collapse: collapse; margin-top: 10px; }\n"
"        th { padding: 10px; text-align: left; border-bottom: 1px solid #444; color: #888; font-size: 13px; }\n"
"        td { padding: 10px; text-align: left; border-bottom: 1px solid #2a2a2a; font-size: 14px; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class='container'>\n"
"        <div class='header'>\n"
"            <h1>🚀 Pure Solo Gateway</h1>\n"
"            <div class='status-indicator'><span class='dot'></span>Node Connected</div>\n"
"        </div>\n"
"        <div class='grid'>\n"
"            <div class='card'>\n"
"                <h3>Total Hashrate</h3>\n"
"                <p id='val-hashrate'>0.00</p>\n"
"                <div class='subtext'>Terrahashes per second (Th/s)</div>\n"
"            </div>\n"
"            <div class='card'>\n"
"                <h3>Active Workers</h3>\n"
"                <p id='val-workers'>0 / 0</p>\n"
"                <div class='subtext'>Subscribed / Total Connections</div>\n"
"            </div>\n"
"            <div class='card'>\n"
"                <h3>Network Difficulty</h3>\n"
"                <p id='val-netdiff'>Loading...</p>\n"
"                <div class='subtext'>Current Mainnet Difficulty</div>\n"
"            </div>\n"
"            <div class='card'>\n"
"                <h3>Current Block Height</h3>\n"
"                <p id='val-height'>Loading...</p>\n"
"                <div class='subtext'>From Local Bitcoind Node</div>\n"
"            </div>\n"
"            <div class='card'>\n"
"                <h3>Block Reward</h3>\n"
"                <p id='val-reward'>0.00 BTC</p>\n"
"                <div class='subtext'>Subsidy + Tx Fees</div>\n"
"            </div>\n"
"            <div class='card' style='grid-column: 1 / -1;'>\n"
"                <h3>Connected Workers Detail</h3>\n"
"                <table>\n"
"                    <thead>\n"
"                        <tr>\n"
"                            <th>User Agent (Firmware)</th>\n"
"                            <th>Hashrate</th>\n"
"                            <th>Best Share Diff</th>\n"
"                        </tr>\n"
"                    </thead>\n"
"                    <tbody id='workers-body'>\n"
"                        <tr><td colspan='3'>Loading workers...</td></tr>\n"
"                    </tbody>\n"
"                </table>\n"
"            </div>\n"
"        </div>\n"
"        <div class='footer'>Gateway Uptime: <span id='val-uptime'>0s</span> | Data updates every 3 seconds</div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        function formatUptime(seconds) {\n"
"            let d = Math.floor(seconds / 86400); seconds %= 86400;\n"
"            let h = Math.floor(seconds / 3600); seconds %= 3600;\n"
"            let m = Math.floor(seconds / 60); seconds %= 60;\n"
"            return (d > 0 ? d + 'd ' : '') + (h > 0 ? h + 'h ' : '') + (m > 0 ? m + 'm ' : '') + seconds + 's';\n"
"        }\n"
"        function formatDiff(diff) {\n"
"            if (!diff) return '0.00';\n"
"            if (diff >= 1e18) return (diff / 1e18).toFixed(2) + ' E';\n"
"            if (diff >= 1e15) return (diff / 1e15).toFixed(2) + ' P';\n"
"            if (diff >= 1e12) return (diff / 1e12).toFixed(2) + ' T';\n"
"            if (diff >= 1e9)  return (diff / 1e9).toFixed(2) + ' G';\n"
"            if (diff >= 1e6)  return (diff / 1e6).toFixed(2) + ' M';\n"
"            if (diff >= 1e3)  return (diff / 1e3).toFixed(2) + ' K';\n"
"            return diff.toFixed(2);\n"
"        }\n"
"        async function fetchStats() {\n"
"            try {\n"
"                const response = await fetch('/api/stats');\n"
"                const data = await response.json();\n"
"                document.getElementById('val-hashrate').innerText = data.hashrate_th_s.toFixed(2);\n"
"                document.getElementById('val-workers').innerText = data.subscriptions + ' / ' + data.connections;\n"
"                document.getElementById('val-netdiff').innerText = formatDiff(data.network_difficulty);\n"
"                document.getElementById('val-height').innerText = data.current_height || 'Syncing...';\n"
"                document.getElementById('val-reward').innerText = (data.current_value_btc ? data.current_value_btc.toFixed(8) : '0.00') + ' BTC';\n"
"                document.getElementById('val-uptime').innerText = formatUptime(data.uptime_seconds);\n"
"            } catch (error) { console.error('Error fetching stats:', error); }\n"
"        }\n"
"        async function fetchWorkers() {\n"
"            try {\n"
"                const response = await fetch('/api/workers');\n"
"                const workers = await response.json();\n"
"                let html = '';\n"
"                if (workers.length === 0) {\n"
"                    html = '<tr><td colspan=\"3\" style=\"text-align:center; color:#666;\">No active workers connected</td></tr>';\n"
"                } else {\n"
"                    workers.forEach(w => {\n"
"                        html += `<tr>\n"
"                            <td style=\"color:#888;\">${w.user_agent}</td>\n"
"                            <td style=\"color:#4caf50; font-weight:bold;\">${w.hashrate.toFixed(2)} TH/s</td>\n"
"                            <td>${formatDiff(w.best_diff)}</td>\n"
"                        </tr>`;\n"
"                    });\n"
"                }\n"
"                document.getElementById('workers-body').innerHTML = html;\n"
"            } catch (error) { console.error('Error fetching workers:', error); }\n"
"        }\n"
"        setInterval(() => { fetchStats(); fetchWorkers(); }, 3000);\n"
"        fetchStats(); fetchWorkers();\n"
"    </script>\n"
"</body>\n"
"</html>";

const char* web_get_html_dashboard(void) {
    return html_dashboard;
}
